import React, { useState } from 'react';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity,
  TextInput, ActivityIndicator, Alert,
} from 'react-native';
import { useMutation } from '@tanstack/react-query';
import { api } from '../../lib/api';

const GOALS = ['Weight Loss', 'Muscle Gain', 'Maintenance', 'Clean Eating', 'High Protein'];
const PREFS = ['Vegetarian', 'Vegan', 'Non-Vegetarian', 'Keto', 'No Restriction'];
const MEALS_OPTIONS = [3, 4, 5, 6];

export default function AIDietScreen({ navigation }: any) {
  const [goal, setGoal] = useState('');
  const [preference, setPreference] = useState('');
  const [mealsPerDay, setMealsPerDay] = useState(4);
  const [allergies, setAllergies] = useState('');
  const [calories, setCalories] = useState('');
  const [generated, setGenerated] = useState<any>(null);

  const genMutation = useMutation({
    mutationFn: (body: any) => api.post('/diet-plans/ai-generate', body) as any,
    onSuccess: (res: any) => setGenerated(res),
    onError: (e: any) => Alert.alert('Generation Failed', e?.message ?? 'Try again'),
  });

  function generate() {
    if (!goal) return Alert.alert('Required', 'Select a diet goal');
    if (!preference) return Alert.alert('Required', 'Select your dietary preference');
    genMutation.mutate({
      goal: goal.toUpperCase().replace(/ /g, '_'),
      dietaryPreference: preference.toUpperCase().replace(/ /g, '_'),
      mealsPerDay,
      allergies: allergies || undefined,
      targetCalories: calories ? parseInt(calories) : undefined,
    });
  }

  if (generated) {
    const meals: any[] = generated.meals ?? generated.dietMeals ?? [];
    return (
      <View style={styles.container}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => setGenerated(null)}><Text style={styles.back}>‹ Edit</Text></TouchableOpacity>
          <View style={styles.headerRow}>
            <Text style={styles.title}>{generated.name ?? 'AI Diet Plan'}</Text>
            <TouchableOpacity
              style={styles.viewBtn}
              onPress={() => navigation.replace('DietDetail', { planId: generated.id, planName: generated.name })}
            >
              <Text style={styles.viewBtnText}>View Full</Text>
            </TouchableOpacity>
          </View>
          <Text style={styles.sub}>✨ Generated by AI</Text>
        </View>
        <ScrollView contentContainerStyle={{ paddingHorizontal: 20, paddingBottom: 40 }}>
          <View style={styles.genCard}>
            <Row label="Goal" value={generated.goal ?? goal} />
            <Row label="Total Calories" value={generated.totalCalories ? `${generated.totalCalories} kcal` : 'Balanced'} />
            <Row label="Meals/Day" value={mealsPerDay.toString()} />
          </View>
          {meals.slice(0, 4).map((meal: any, i: number) => (
            <View key={i} style={styles.mealCard}>
              <Text style={styles.mealTime}>{meal.mealTime ?? meal.timeSlot ?? `Meal ${i + 1}`}</Text>
              <Text style={styles.mealName}>{meal.name ?? meal.foodItem}</Text>
              {meal.calories && <Text style={styles.mealCals}>{meal.calories} kcal</Text>}
            </View>
          ))}
          {meals.length > 4 && (
            <Text style={styles.moreText}>+{meals.length - 4} more meals — tap View Full</Text>
          )}
        </ScrollView>
      </View>
    );
  }

  return (
    <ScrollView style={styles.container} contentContainerStyle={{ paddingBottom: 60 }}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>‹ Back</Text></TouchableOpacity>
        <Text style={styles.title}>AI Diet Generator</Text>
        <Text style={styles.sub}>Get a personalized nutrition plan</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionLabel}>Diet Goal</Text>
        <View style={styles.chipRow}>
          {GOALS.map((g) => (
            <TouchableOpacity key={g} style={[styles.chip, goal === g && styles.chipActive]} onPress={() => setGoal(g)}>
              <Text style={[styles.chipText, goal === g && styles.chipTextActive]}>{g}</Text>
            </TouchableOpacity>
          ))}
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionLabel}>Dietary Preference</Text>
        <View style={styles.chipRow}>
          {PREFS.map((p) => (
            <TouchableOpacity key={p} style={[styles.chip, preference === p && styles.chipActive]} onPress={() => setPreference(p)}>
              <Text style={[styles.chipText, preference === p && styles.chipTextActive]}>{p}</Text>
            </TouchableOpacity>
          ))}
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionLabel}>Meals per Day</Text>
        <View style={styles.chipRow}>
          {MEALS_OPTIONS.map((m) => (
            <TouchableOpacity key={m} style={[styles.chip, mealsPerDay === m && styles.chipActive]} onPress={() => setMealsPerDay(m)}>
              <Text style={[styles.chipText, mealsPerDay === m && styles.chipTextActive]}>{m} meals</Text>
            </TouchableOpacity>
          ))}
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionLabel}>Target Calories (optional)</Text>
        <TextInput
          style={styles.input}
          value={calories}
          onChangeText={setCalories}
          keyboardType="number-pad"
          placeholder="e.g., 2000"
          placeholderTextColor="#4B5563"
        />
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionLabel}>Allergies / Restrictions (optional)</Text>
        <TextInput
          style={styles.input}
          value={allergies}
          onChangeText={setAllergies}
          placeholder="e.g., nuts, dairy, gluten…"
          placeholderTextColor="#4B5563"
        />
      </View>

      <TouchableOpacity
        style={[styles.genBtn, genMutation.isPending && styles.genBtnDisabled]}
        onPress={generate}
        disabled={genMutation.isPending}
      >
        {genMutation.isPending ? (
          <View style={{ flexDirection: 'row', gap: 10, alignItems: 'center' }}>
            <ActivityIndicator color="#fff" size="small" />
            <Text style={styles.genBtnText}>Generating…</Text>
          </View>
        ) : (
          <Text style={styles.genBtnText}>✨ Generate Diet Plan</Text>
        )}
      </TouchableOpacity>
    </ScrollView>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <View style={{ flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 6 }}>
      <Text style={{ color: '#9CA3AF', fontSize: 13 }}>{label}</Text>
      <Text style={{ color: '#F9FAFB', fontSize: 13, fontWeight: '600' }}>{value}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0F0F0F' },
  header: { paddingTop: 56, paddingHorizontal: 20, marginBottom: 24 },
  back: { color: '#FF4D00', fontSize: 16, marginBottom: 10 },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  title: { color: '#F9FAFB', fontSize: 22, fontWeight: '700', flex: 1 },
  sub: { color: '#9CA3AF', fontSize: 13, marginTop: 4 },
  viewBtn: { backgroundColor: '#FF4D00', borderRadius: 8, paddingHorizontal: 14, paddingVertical: 8 },
  viewBtnText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  section: { paddingHorizontal: 20, marginBottom: 24 },
  sectionLabel: { color: '#9CA3AF', fontSize: 12, fontWeight: '600', marginBottom: 12, textTransform: 'uppercase', letterSpacing: 0.5 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { paddingHorizontal: 14, paddingVertical: 9, borderRadius: 10, backgroundColor: '#1A1A1A', borderWidth: 1, borderColor: '#2A2A2A' },
  chipActive: { backgroundColor: '#FF4D00', borderColor: '#FF4D00' },
  chipText: { color: '#9CA3AF', fontSize: 13, fontWeight: '600' },
  chipTextActive: { color: '#fff' },
  input: {
    backgroundColor: '#1A1A1A', borderRadius: 12, borderWidth: 1,
    borderColor: '#2A2A2A', color: '#F9FAFB', fontSize: 14,
    paddingHorizontal: 16, paddingVertical: 12,
  },
  genBtn: { marginHorizontal: 20, backgroundColor: '#FF4D00', borderRadius: 16, paddingVertical: 18, alignItems: 'center' },
  genBtnDisabled: { opacity: 0.6 },
  genBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  genCard: { backgroundColor: '#1A1A1A', borderRadius: 14, padding: 16, marginBottom: 16, borderWidth: 1, borderColor: '#2A2A2A' },
  mealCard: { backgroundColor: '#1A1A1A', borderRadius: 12, padding: 14, marginBottom: 8, borderWidth: 1, borderColor: '#2A2A2A', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  mealTime: { color: '#FF4D00', fontSize: 11, fontWeight: '700', width: 90 },
  mealName: { color: '#F9FAFB', fontSize: 13, flex: 1 },
  mealCals: { color: '#6B7280', fontSize: 12 },
  moreText: { color: '#4B5563', fontSize: 13, textAlign: 'center', marginTop: 8 },
});
