import React, { useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { useMutation } from '@tanstack/react-query';
import { api } from '../../lib/api';
import { Button, Card, Chip, ChipRow, Field, Header, Screen, TextField } from '../../components';
import { colors, spacing, typography } from '../../theme';

const GOALS = ['Weight Loss', 'Muscle Gain', 'Maintenance', 'Clean Eating', 'High Protein'];
const PREFS = ['Vegetarian', 'Vegan', 'Non-Vegetarian', 'Keto', 'No Restriction'];
const MEALS_OPTIONS = [3, 4, 5, 6];

export default function AIDietScreen({ navigation }: any) {
  const [goal, setGoal] = useState('');
  const [preference, setPreference] = useState('');
  const [mealsPerDay, setMealsPerDay] = useState(4);
  const [allergies, setAllergies] = useState('');
  const [calories, setCalories] = useState('');
  const [generated, setGenerated] = useState<any>(null);

  const genMutation = useMutation({
    mutationFn: (body: any) => api.post('/diet-plans/ai-generate', body) as any,
    onSuccess: (res: any) => setGenerated(res),
    onError: (e: any) => Alert.alert('Generation Failed', e?.message ?? 'Try again'),
  });

  function generate() {
    if (!goal) return Alert.alert('Required', 'Select a diet goal');
    if (!preference) return Alert.alert('Required', 'Select your dietary preference');
    genMutation.mutate({
      goal: goal.toUpperCase().replace(/ /g, '_'),
      dietaryPreference: preference.toUpperCase().replace(/ /g, '_'),
      mealsPerDay,
      allergies: allergies || undefined,
      calories: calories ? parseInt(calories, 10) : undefined,
    });
  }

  if (generated) {
    const meals: any[] = generated.meals ?? generated.dietMeals ?? [];
    return (
      <Screen scroll>
        <Header
          title={generated.name ?? 'AI Diet Plan'}
          subtitle="Generated by AI"
          onBack={() => setGenerated(null)}
          right={<Button title="View full" onPress={() => navigation.replace('DietDetail', { planId: generated.id, planName: generated.name })} />}
        />
        <Card>
          <Row label="Goal" value={String(generated.goal ?? goal).replace(/_/g, ' ')} />
          <Row label="Total calories" value={generated.totalCalories ? `${generated.totalCalories} kcal` : 'Balanced'} />
          <Row label="Meals / day" value={String(mealsPerDay)} last />
        </Card>
        {meals.slice(0, 4).map((meal: any, i: number) => (
          <Card key={i} padding="md" style={styles.mealCard}>
            <Text style={styles.mealTime}>{meal.meal ?? `Meal ${i + 1}`}</Text>
            <Text style={styles.mealName} numberOfLines={2}>
              {Array.isArray(meal.items) ? meal.items.join(', ') : (meal.name ?? meal.foodItem ?? '')}
            </Text>
            {meal.calories ? <Text style={styles.mealCals}>{meal.calories} kcal</Text> : null}
          </Card>
        ))}
        {meals.length > 4 ? <Text style={styles.moreText}>+{meals.length - 4} more meals — tap View full</Text> : null}
      </Screen>
    );
  }

  return (
    <Screen scroll keyboard>
      <Header title="AI Diet Generator" subtitle="Get a personalized nutrition plan" onBack={() => navigation.goBack()} />

      <Field label="Diet goal">
        <ChipRow>{GOALS.map((g) => <Chip key={g} label={g} selected={goal === g} onPress={() => setGoal(g)} />)}</ChipRow>
      </Field>
      <Field label="Dietary preference">
        <ChipRow>{PREFS.map((p) => <Chip key={p} label={p} selected={preference === p} onPress={() => setPreference(p)} />)}</ChipRow>
      </Field>
      <Field label="Meals per day">
        <ChipRow>{MEALS_OPTIONS.map((m) => <Chip key={m} label={`${m} meals`} selected={mealsPerDay === m} onPress={() => setMealsPerDay(m)} />)}</ChipRow>
      </Field>
      <Field label="Target calories (optional)">
        <TextField value={calories} onChangeText={setCalories} keyboardType="number-pad" placeholder="e.g., 2000" />
      </Field>
      <Field label="Allergies / restrictions (optional)">
        <TextField value={allergies} onChangeText={setAllergies} placeholder="e.g., nuts, dairy, gluten…" />
      </Field>

      <Button title={genMutation.isPending ? 'Generating…' : 'Generate diet plan'} icon="zap" size="lg" onPress={generate} loading={genMutation.isPending} />
    </Screen>
  );
}

function Row({ label, value, last }: { label: string; value?: string; last?: boolean }) {
  return (
    <View style={[styles.row, !last && styles.rowBorder]}>
      <Text style={styles.rowLabel}>{label}</Text>
      <Text style={styles.rowValue}>{value ?? '—'}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8 },
  rowBorder: { borderBottomWidth: 1, borderBottomColor: colors.border },
  rowLabel: { color: colors.textSecondary, ...typography.label },
  rowValue: { color: colors.text, ...typography.label, fontWeight: '600', textTransform: 'capitalize' },
  mealCard: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  mealTime: { color: colors.primary, ...typography.micro, fontWeight: '700', width: 90 },
  mealName: { color: colors.text, ...typography.label, flex: 1 },
  mealCals: { color: colors.textMuted, ...typography.caption, ...typography.number },
  moreText: { color: colors.textFaint, ...typography.label, textAlign: 'center', marginTop: spacing.sm },
});
