import React, { useState } from 'react';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity,
  TextInput, ActivityIndicator, Alert,
} from 'react-native';
import { useMutation } from '@tanstack/react-query';
import { api } from '../../lib/api';

const GOALS = ['Weight Loss', 'Muscle Gain', 'Endurance', 'Flexibility', 'General Fitness'];
const LEVELS = ['Beginner', 'Intermediate', 'Advanced'];
const DAYS_OPTIONS = [3, 4, 5, 6];

export default function AIWorkoutScreen({ navigation }: any) {
  const [goal, setGoal] = useState('');
  const [level, setLevel] = useState('');
  const [daysPerWeek, setDaysPerWeek] = useState(4);
  const [equipment, setEquipment] = useState('');
  const [generated, setGenerated] = useState<any>(null);

  const genMutation = useMutation({
    mutationFn: (body: any) => api.post('/workout-plans/ai-generate', body) as any,
    onSuccess: (res: any) => setGenerated(res),
    onError: (e: any) => Alert.alert('Generation Failed', e?.message ?? 'Try again'),
  });

  function generate() {
    if (!goal) return Alert.alert('Required', 'Select a fitness goal');
    if (!level) return Alert.alert('Required', 'Select your fitness level');
    genMutation.mutate({
      goal: goal.toUpperCase().replace(/ /g, '_'),
      fitnessLevel: level.toUpperCase(),
      daysPerWeek,
      equipment: equipment || undefined,
    });
  }

  if (generated) {
    return (
      <View style={styles.container}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => setGenerated(null)}><Text style={styles.back}>‹ Edit</Text></TouchableOpacity>
          <View style={styles.headerRow}>
            <Text style={styles.title}>{generated.name ?? 'AI Workout Plan'}</Text>
            <TouchableOpacity
              style={styles.viewBtn}
              onPress={() => navigation.replace('WorkoutDetail', { planId: generated.id, planName: generated.name })}
            >
              <Text style={styles.viewBtnText}>View Full</Text>
            </TouchableOpacity>
          </View>
          <Text style={styles.sub}>✨ Generated by AI</Text>
        </View>
        <ScrollView contentContainerStyle={{ paddingHorizontal: 20, paddingBottom: 40 }}>
          <View style={styles.genCard}>
            <Row label="Goal" value={generated.goal} />
            <Row label="Difficulty" value={generated.difficulty} />
            <Row label="Days/Week" value={daysPerWeek.toString()} />
          </View>
          {(generated.workoutDays ?? []).slice(0, 3).map((day: any, i: number) => (
            <View key={i} style={styles.dayCard}>
              <Text style={styles.dayName}>{day.dayName ?? `Day ${i + 1}`}</Text>
              <Text style={styles.dayExCount}>{day.exercises?.length ?? 0} exercises</Text>
              {(day.exercises ?? []).slice(0, 2).map((ex: any, j: number) => (
                <Text key={j} style={styles.exPreview}>· {ex.name ?? ex.exerciseName}</Text>
              ))}
              {(day.exercises?.length ?? 0) > 2 && (
                <Text style={styles.exMore}>+{day.exercises.length - 2} more</Text>
              )}
            </View>
          ))}
          {(generated.workoutDays?.length ?? 0) > 3 && (
            <Text style={styles.moreText}>+{generated.workoutDays.length - 3} more days — tap View Full</Text>
          )}
        </ScrollView>
      </View>
    );
  }

  return (
    <ScrollView style={styles.container} contentContainerStyle={{ paddingBottom: 60 }}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>‹ Back</Text></TouchableOpacity>
        <Text style={styles.title}>AI Workout Generator</Text>
        <Text style={styles.sub}>Describe your goals and get a personalized plan</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionLabel}>Fitness Goal</Text>
        <View style={styles.chipRow}>
          {GOALS.map((g) => (
            <TouchableOpacity
              key={g} style={[styles.chip, goal === g && styles.chipActive]}
              onPress={() => setGoal(g)}
            >
              <Text style={[styles.chipText, goal === g && styles.chipTextActive]}>{g}</Text>
            </TouchableOpacity>
          ))}
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionLabel}>Fitness Level</Text>
        <View style={styles.chipRow}>
          {LEVELS.map((l) => (
            <TouchableOpacity
              key={l} style={[styles.chip, level === l && styles.chipActive]}
              onPress={() => setLevel(l)}
            >
              <Text style={[styles.chipText, level === l && styles.chipTextActive]}>{l}</Text>
            </TouchableOpacity>
          ))}
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionLabel}>Days per Week</Text>
        <View style={styles.chipRow}>
          {DAYS_OPTIONS.map((d) => (
            <TouchableOpacity
              key={d} style={[styles.chip, daysPerWeek === d && styles.chipActive]}
              onPress={() => setDaysPerWeek(d)}
            >
              <Text style={[styles.chipText, daysPerWeek === d && styles.chipTextActive]}>{d} days</Text>
            </TouchableOpacity>
          ))}
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionLabel}>Equipment Available (optional)</Text>
        <TextInput
          style={styles.input}
          value={equipment}
          onChangeText={setEquipment}
          placeholder="e.g., dumbbells, barbell, resistance bands…"
          placeholderTextColor="#4B5563"
        />
      </View>

      <TouchableOpacity
        style={[styles.genBtn, genMutation.isPending && styles.genBtnDisabled]}
        onPress={generate}
        disabled={genMutation.isPending}
      >
        {genMutation.isPending ? (
          <View style={{ flexDirection: 'row', gap: 10, alignItems: 'center' }}>
            <ActivityIndicator color="#fff" size="small" />
            <Text style={styles.genBtnText}>Generating…</Text>
          </View>
        ) : (
          <Text style={styles.genBtnText}>✨ Generate Plan</Text>
        )}
      </TouchableOpacity>
    </ScrollView>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <View style={{ flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 6 }}>
      <Text style={{ color: '#9CA3AF', fontSize: 13 }}>{label}</Text>
      <Text style={{ color: '#F9FAFB', fontSize: 13, fontWeight: '600' }}>{value}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0F0F0F' },
  header: { paddingTop: 56, paddingHorizontal: 20, marginBottom: 24 },
  back: { color: '#FF4D00', fontSize: 16, marginBottom: 10 },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  title: { color: '#F9FAFB', fontSize: 22, fontWeight: '700', flex: 1 },
  sub: { color: '#9CA3AF', fontSize: 13, marginTop: 4 },
  viewBtn: { backgroundColor: '#FF4D00', borderRadius: 8, paddingHorizontal: 14, paddingVertical: 8 },
  viewBtnText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  section: { paddingHorizontal: 20, marginBottom: 24 },
  sectionLabel: { color: '#9CA3AF', fontSize: 12, fontWeight: '600', marginBottom: 12, textTransform: 'uppercase', letterSpacing: 0.5 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    paddingHorizontal: 14, paddingVertical: 9, borderRadius: 10,
    backgroundColor: '#1A1A1A', borderWidth: 1, borderColor: '#2A2A2A',
  },
  chipActive: { backgroundColor: '#FF4D00', borderColor: '#FF4D00' },
  chipText: { color: '#9CA3AF', fontSize: 13, fontWeight: '600' },
  chipTextActive: { color: '#fff' },
  input: {
    backgroundColor: '#1A1A1A', borderRadius: 12, borderWidth: 1,
    borderColor: '#2A2A2A', color: '#F9FAFB', fontSize: 14,
    paddingHorizontal: 16, paddingVertical: 12,
  },
  genBtn: {
    marginHorizontal: 20, backgroundColor: '#FF4D00', borderRadius: 16,
    paddingVertical: 18, alignItems: 'center',
  },
  genBtnDisabled: { opacity: 0.6 },
  genBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  genCard: {
    backgroundColor: '#1A1A1A', borderRadius: 14, padding: 16,
    marginBottom: 16, borderWidth: 1, borderColor: '#2A2A2A',
  },
  dayCard: {
    backgroundColor: '#1A1A1A', borderRadius: 12, padding: 14,
    marginBottom: 10, borderWidth: 1, borderColor: '#2A2A2A',
  },
  dayName: { color: '#F9FAFB', fontSize: 14, fontWeight: '700', marginBottom: 4 },
  dayExCount: { color: '#FF4D00', fontSize: 12, marginBottom: 8 },
  exPreview: { color: '#9CA3AF', fontSize: 12, marginBottom: 2 },
  exMore: { color: '#6B7280', fontSize: 12, marginTop: 4 },
  moreText: { color: '#4B5563', fontSize: 13, textAlign: 'center', marginTop: 8 },
});
