import React, { useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { useMutation } from '@tanstack/react-query';
import { api } from '../../lib/api';
import { Button, Card, Chip, ChipRow, Field, Header, Screen, TextField } from '../../components';
import { colors, spacing, typography } from '../../theme';

const GOALS = ['Weight Loss', 'Muscle Gain', 'Endurance', 'Flexibility', 'General Fitness'];
const LEVELS = ['Beginner', 'Intermediate', 'Advanced'];
const DAYS_OPTIONS = [3, 4, 5, 6];

export default function AIWorkoutScreen({ navigation }: any) {
  const [goal, setGoal] = useState('');
  const [level, setLevel] = useState('');
  const [daysPerWeek, setDaysPerWeek] = useState(4);
  const [equipment, setEquipment] = useState('');
  const [generated, setGenerated] = useState<any>(null);

  const genMutation = useMutation({
    mutationFn: (body: any) => api.post('/workout-plans/ai-generate', body) as any,
    onSuccess: (res: any) => setGenerated(res),
    onError: (e: any) => Alert.alert('Generation Failed', e?.message ?? 'Try again'),
  });

  function generate() {
    if (!goal) return Alert.alert('Required', 'Select a fitness goal');
    if (!level) return Alert.alert('Required', 'Select your fitness level');
    genMutation.mutate({
      goal: goal.toUpperCase().replace(/ /g, '_'),
      level: level.toUpperCase(),
      daysPerWeek,
      equipment: equipment || undefined,
    });
  }

  if (generated) {
    const allEx: any[] = generated.exercises ?? [];
    const days = Array.from(new Set(allEx.map((e: any) => e.day)));
    return (
      <Screen scroll>
        <Header
          title={generated.name ?? 'AI Workout Plan'}
          subtitle="Generated by AI"
          onBack={() => setGenerated(null)}
          right={<Button title="View full" size="md" onPress={() => navigation.replace('WorkoutDetail', { planId: generated.id, planName: generated.name })} />}
        />
        <Card>
          <Row label="Goal" value={String(generated.goal ?? '').replace(/_/g, ' ')} />
          <Row label="Difficulty" value={generated.difficulty} />
          <Row label="Days / week" value={String(daysPerWeek)} last />
        </Card>
        {days.slice(0, 3).map((day: any) => {
          const dayEx = allEx.filter((e: any) => e.day === day);
          return (
            <Card key={day} padding="md">
              <Text style={styles.dayName}>{day}</Text>
              <Text style={styles.dayCount}>{dayEx.length} exercises</Text>
              {dayEx.slice(0, 2).map((ex: any, j: number) => <Text key={j} style={styles.exPreview}>· {ex.name}</Text>)}
              {dayEx.length > 2 ? <Text style={styles.exMore}>+{dayEx.length - 2} more</Text> : null}
            </Card>
          );
        })}
        {days.length > 3 ? <Text style={styles.moreText}>+{days.length - 3} more days — tap View full</Text> : null}
      </Screen>
    );
  }

  return (
    <Screen scroll keyboard>
      <Header title="AI Workout Generator" subtitle="Describe your goals and get a personalized plan" onBack={() => navigation.goBack()} />

      <Field label="Fitness goal">
        <ChipRow>{GOALS.map((g) => <Chip key={g} label={g} selected={goal === g} onPress={() => setGoal(g)} />)}</ChipRow>
      </Field>
      <Field label="Fitness level">
        <ChipRow>{LEVELS.map((l) => <Chip key={l} label={l} selected={level === l} onPress={() => setLevel(l)} />)}</ChipRow>
      </Field>
      <Field label="Days per week">
        <ChipRow>{DAYS_OPTIONS.map((d) => <Chip key={d} label={`${d} days`} selected={daysPerWeek === d} onPress={() => setDaysPerWeek(d)} />)}</ChipRow>
      </Field>
      <Field label="Equipment available (optional)">
        <TextField value={equipment} onChangeText={setEquipment} placeholder="e.g., dumbbells, barbell, resistance bands…" />
      </Field>

      <Button title={genMutation.isPending ? 'Generating…' : 'Generate plan'} icon="zap" size="lg" onPress={generate} loading={genMutation.isPending} />
    </Screen>
  );
}

function Row({ label, value, last }: { label: string; value?: string; last?: boolean }) {
  return (
    <View style={[styles.row, !last && styles.rowBorder]}>
      <Text style={styles.rowLabel}>{label}</Text>
      <Text style={styles.rowValue}>{value ?? '—'}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8 },
  rowBorder: { borderBottomWidth: 1, borderBottomColor: colors.border },
  rowLabel: { color: colors.textSecondary, ...typography.label },
  rowValue: { color: colors.text, ...typography.label, fontWeight: '600', textTransform: 'capitalize' },
  dayName: { color: colors.text, ...typography.body, fontWeight: '700', marginBottom: 2 },
  dayCount: { color: colors.primary, ...typography.caption, marginBottom: spacing.sm },
  exPreview: { color: colors.textSecondary, ...typography.caption, marginBottom: 2 },
  exMore: { color: colors.textMuted, ...typography.caption, marginTop: 4 },
  moreText: { color: colors.textFaint, ...typography.label, textAlign: 'center', marginTop: spacing.sm },
});
